2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_setup.py:_flush():67] Configure stats pid to 2292
2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_setup.py:_flush():67] Loading settings from C:\Users\Siddhant\.config\wandb\settings
2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_setup.py:_flush():67] Loading settings from C:\da24m021_da6401_assignment1\wandb\settings
2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-27 09:55:57,729 INFO    MainThread:2292 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\da24m021_da6401_assignment1\wandb\run-20250227_095557-63h9qtwj\logs\debug.log
2025-02-27 09:55:57,738 INFO    MainThread:2292 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\da24m021_da6401_assignment1\wandb\run-20250227_095557-63h9qtwj\logs\debug-internal.log
2025-02-27 09:55:57,738 INFO    MainThread:2292 [wandb_init.py:init():761] calling init triggers
2025-02-27 09:55:57,738 INFO    MainThread:2292 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-02-27 09:55:57,738 INFO    MainThread:2292 [wandb_init.py:init():784] starting backend
2025-02-27 09:55:57,738 INFO    MainThread:2292 [wandb_init.py:init():788] sending inform_init request
2025-02-27 09:55:57,795 INFO    MainThread:2292 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2025-02-27 09:55:57,811 INFO    MainThread:2292 [wandb_init.py:init():803] backend started and connected
2025-02-27 09:55:57,813 INFO    MainThread:2292 [wandb_init.py:init():896] updated telemetry
2025-02-27 09:55:57,872 INFO    MainThread:2292 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-27 09:55:58,527 ERROR   MainThread:2292 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-02-27 09:55:58,549 WARNING MsgRouterThr:2292 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Siddhant\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-27 09:55:58,550 INFO    MsgRouterThr:2292 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
